export const CONTENT_TYPE = 'Content-type'
export const CLIENT_ID = 'client_id'
export const CLIENT_SECRET = 'client_secret'
export const GRANT_TYPE = 'grant_type'
export const AUTHORIZATION = 'Authorization'
export const PASSWORD = 'password'
export const USERNAME = 'username'
