export enum routes {
  CLIENT_HOME = '/cliente',
  CLIENT_LOGIN = '/cliente/login',
  CLIENT_SCHEDULE = '/cliente/agendar',
  CLIENT_SCHEDULE_SERVICE = '/cliente/agendar/servicos',
  CLIENT_SCHEDULE_PROFESSIONAL = 'cliente/agendar/profissionais',
  CLIENT_SCHEDULE_TIME = 'cliente/agendar/horarios',
  CLIENT_SCHEDULE_CONFIRM = 'cliente/agendar/confirmacao',
  ADMIN_HOME = '/admin',
  ADMIN_SCHEDULES = 'admin/agendamentos',
  ADMIN_CONFIGURATIONS = 'admin/configuracoes',
  ADMIN_REGISTER_SERVICE = '/admin/cadastrar/servicos',
  ADMIN_REGISTER_PROFESSIONAL = '/admin/cadastrar/profissionais',
  ADMIN_REGISTER_TIME = '/admin/cadastrar/horarios',
  ADMIN_ADD_SERVICE = '/admin/cadastrar/adicionar-servico',
  ADMIN_REMOVE_SERVICE = '/admin/cadastrar/remover-servico',
  ADMIN_ADD_PROFESSIONAL = '/admin/cadastrar/adicionar-profissional',
  ADMIN_REMOVE_PROFESSIONAL = '/admin/cadastrar/remover-profissional',
  ADMIN_ADD_TIME = '/admin/cadastrar/adicionar-horario',
  ADMIN_REMOVE_TIME = '/admin/cadastrar/remover-horario'
}
